export const bets = [
    // Good Bets (Traditional Charities)
    {
        id: "100159231",
        isEvil: false,
        title: "Medical Research vs Direct Care: Who receives the majority by March 31?",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=Medical",
        chance: 80,
        optionA: { name: "Research Grants" },
        optionB: { name: "Direct Patient Care" },
        vol: "$34M Vol.",
        hasCircle: true,
        tags: ["Trending", "Science"],
        timeRemaining: "12 hours left"
    },
    {
        id: "100234198",
        isEvil: false,
        title: "Global Tech Access: One Laptop per Child vs Code.org",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=TechAccess",
        chance: 60,
        optionA: { name: "OLPC" },
        optionB: { name: "Code.org" },
        vol: "$12M Vol.",
        hasCircle: false,
        tags: ["Culture", "New"],
        timeRemaining: "3 days left"
    },
    {
        id: "100344111",
        isEvil: false,
        title: "Ocean Conservation: Ocean Conservancy vs Coral Reef Alliance",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=Ocean",
        chance: 45,
        optionA: { name: "Conservancy" },
        optionB: { name: "Coral Alliance" },
        vol: "$8M Vol.",
        hasCircle: false,
        tags: ["Climate & Science", "Trending"],
        timeRemaining: "7 days left"
    },
    {
        id: "100411222",
        isEvil: false,
        title: "Wildlife Protection: WWF vs Wildlife Conservation Society",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=Wildlife",
        chance: 90,
        optionA: { name: "WWF" },
        optionB: { name: "WCS" },
        vol: "$45M Vol.",
        hasCircle: true,
        tags: ["Breaking", "Climate & Science"],
        timeRemaining: "2 days left"
    },
    {
        id: "100529991",
        isEvil: false,
        title: "Disaster Relief: Red Cross vs Direct Relief",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=Disaster2",
        chance: 55,
        optionA: { name: "Red Cross" },
        optionB: { name: "Direct Relief" },
        vol: "$21M Vol.",
        hasCircle: true,
        tags: ["Trending", "Expiring Soon"],
        timeRemaining: "4 hours left"
    },
    {
        id: "100654312",
        isEvil: false,
        title: "Clean Water: Water.org vs The Water Project",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=Water2",
        chance: 70,
        optionA: { name: "Water.org" },
        optionB: { name: "Water Project" },
        vol: "$5M Vol.",
        hasCircle: false,
        tags: ["Science", "Culture"],
        timeRemaining: "15 days left"
    },

    // "Evil" Bets (Controversial or Aggressive Action Charities)
    {
        id: "900133441",
        isEvil: true,
        title: "Aggressive Environmental Tactics vs Legal Lobbying",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=Politics1",
        chance: 48,
        optionA: { name: "Greenpeace Direct Action" },
        optionB: { name: "Earthjustice Lawyers" },
        vol: "$142M Vol.",
        hasCircle: true,
        tags: ["Politics", "Breaking"],
        timeRemaining: "1 day left"
    },
    {
        id: "900259832",
        isEvil: true,
        title: "Animal Testing Alternatives vs Aggressive PETA Campaigns",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=Conflict1",
        chance: 35,
        optionA: { name: "Cruelty Free Int'l" },
        optionB: { name: "PETA Foundation" },
        vol: "$89M Vol.",
        hasCircle: false,
        tags: ["Culture", "Trending"],
        timeRemaining: "5 days left"
    },
    {
        id: "900388273",
        isEvil: true,
        title: "AI Safety: Open Source Democratization vs Strict AI Alignment",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=Energy1",
        chance: 62,
        optionA: { name: "Open Source AI" },
        optionB: { name: "Alignment Research Center" },
        vol: "$210M Vol.",
        hasCircle: true,
        tags: ["Science", "New"],
        timeRemaining: "14 days left"
    },
    {
        id: "900412354",
        isEvil: true,
        title: "Private Space Exploitation vs Orbital Debris Cleanup",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=TechReg",
        chance: 21,
        optionA: { name: "Asteroid Mining Lobby" },
        optionB: { name: "Clean Orbit Initiative" },
        vol: "$45M Vol.",
        hasCircle: false,
        tags: ["Climate & Science", "Expiring Soon"],
        timeRemaining: "2 hours left"
    },
    {
        id: "900599185",
        isEvil: true,
        title: "Aggressive Corporate Whistleblowing vs Reform Think-Tanks",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=Space",
        chance: 77,
        optionA: { name: "WikiLeaks Defense" },
        optionB: { name: "Brookings Institute" },
        vol: "$60M Vol.",
        hasCircle: true,
        tags: ["Politics", "Trending"],
        timeRemaining: "8 days left"
    },
    {
        id: "900645606",
        isEvil: true,
        title: "Defending Controversial Free Speech vs Moderation Coalitions",
        image: "https://api.dicebear.com/7.x/identicon/svg?seed=Policy",
        chance: 58,
        optionA: { name: "EFF Defense" },
        optionB: { name: "Center for Comms" },
        vol: "$325M Vol.",
        hasCircle: false,
        tags: ["Politics", "Culture"],
        timeRemaining: "21 days left"
    }
];
